name: Validate Lesson

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout student code
        uses: actions/checkout@v3

      - name: Get test binary
        run: |
          curl -o test_binary.tar.gz https://test-binary.codeling.dev/cicd_test_binary.tar.gz
          tar xzf test_binary.tar.gz
          chmod +x test_binary

      - name: Setup test binary
        run: ./test_binary -command setup

      - name: Setup Python
        if: ${{ env.COURSE_VARIANT_CODE == 'python' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run tests
        run: ./test_binary -command test